apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: farzana_http
        image: farzanarahman/building_image:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  selector:
    app: http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30085
  type: NodePort